<?php
//intanciando os objetos
$usuarioController = new UsuarioController();
$usuarioModel = new Usuario();

//mostra a mensagem verdadeiro ou falso na hora do cadastro
$resultado = "";

$btnCadastrar = filter_input(INPUT_POST, "btnCadastrar", FILTER_SANITIZE_STRING);

if ($btnCadastrar):
    $usuarioModel->setCod(filter_input(INPUT_GET, "cod", FILTER_SANITIZE_NUMBER_INT));
    $usuarioModel->setUsuario(filter_input(INPUT_POST, "txtUsuario", FILTER_SANITIZE_STRING));
    $usuarioModel->setEmail(filter_input(INPUT_POST, "txtEmail", FILTER_SANITIZE_STRING));
    $usuarioModel->setStatus(filter_input(INPUT_POST, "slStatus", FILTER_SANITIZE_NUMBER_INT));
    $usuarioModel->setNome(filter_input(INPUT_POST, "txtNome", FILTER_SANITIZE_STRING));    
    $usuarioModel->setNivel(filter_input(INPUT_POST, "slNivel", FILTER_SANITIZE_NUMBER_INT));
    $usuarioModel->setCep(filter_input(INPUT_POST, "txtCep", FILTER_SANITIZE_STRING));
    $usuarioModel->setBairro(filter_input(INPUT_POST, "txtBairro", FILTER_SANITIZE_STRING));
    $usuarioModel->setCidade(filter_input(INPUT_POST, "txtCidade", FILTER_SANITIZE_STRING));
    $usuarioModel->setEndereco(filter_input(INPUT_POST, "txtEndereco", FILTER_SANITIZE_STRING));
    $usuarioModel->setEstado(filter_input(INPUT_POST, "txtEstado", FILTER_SANITIZE_STRING));
    $usuarioModel->setData(date('Y-m-d H:i:s'));
    
    

    
    if ($usuarioController->Atualizar($usuarioModel)):
        $resultado = '<div class="alert alert-info">
            <button type="button" aria-hidden="true" class="close">×</button>
            <span><b> Atualizado com sucesso - </b></span>
        </div>';
    else:
        $resultado = '<div class="alert alert-danger">
            <button type="button" aria-hidden="true" class="close">×</button>
            <span><b> Erro ao atualizar, tente mais tarde - </b></span>
        </div>';
    endif;
    
        

endif;



//listando os usuarios
$listaUsuario = $usuarioController->ListarUsuario();

//retorna dado do Usuario
$cod = filter_input(INPUT_GET, 'cod', FILTER_SANITIZE_NUMBER_INT);
$retornaUsuario = $usuarioController->retornaUsuario($cod);

$usuario = $retornaUsuario->getUsuario();
$email = $retornaUsuario->getEmail();
$status = $retornaUsuario->getStatus();
$nome = $retornaUsuario->getNome();
$nivel = $retornaUsuario->getNivel();
$cep = $retornaUsuario->getCep();
$bairro = $retornaUsuario->getBairro();
$cidade = $retornaUsuario->getCidade();
$endereco = $retornaUsuario->getEndereco();
$estado = $retornaUsuario->getEstado();


?>

<div class="main-panel">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Perfil Usuário</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="#">Perfil Usuário</a>
            </div>
            <?php require_once './inc/header_top.php'; ?>
        </div>
    </nav>


    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-5">

                    <div class="card">
                        <div class="header">
                            <h4 class="title">Usuário Cadastrado</h4>
                        </div>
                        <div class="content">
                            <ul class="list-unstyled team-members">
                                 <?php 
                                        if($listaUsuario == null):
                                            echo 
                                            '<div class="alert alert-warning">
                                                <button type="button" aria-hidden="true" class="close">×</button>
                                                <span><b> Não existe - </b> usuário cadastrado nesse momento</span>
                                            </div>';
                                        else:
                                            foreach ($listaUsuario as $user):                                           
                                            
                                        
                                    ?>
                                <li>
                                   
                                    <div class="row">
                                        <div class="col-xs-2">
                                            <div class="avatar">
                                                <img src="assets/img/faces/face-0.jpg" alt="Circle Image" class="img-circle img-no-padding img-responsive">
                                                <br />
                                            <span class="text-muted"><small>Offline</small></span>
                                            </div>
                                        </div>
                                        
                                        <div class="col-xs-2">
                                            <?= $user->getUsuario();?>                                           
                                        </div>
                                        <div class="col-xs-2">
                                            <?= $user->getEmail();?>                                           
                                        </div>
                                        <div class="col-xs-2">
                                            <?= $user->getNivel()== 1 ? 'Admin' : 'Super Admin';?>                                           
                                        </div>
                                        <div class="col-xs-2">
                                            <?php echo date('d/m/Y H:i:s', strtotime($user->getData())) ?>                                           
                                        </div>

                                        <div class="col-xs-1 text-center">
                                            <?= $user->getStatus() == 1 ? '<btn class="btn btn-sm btn-success btn-icon"><i class="fa ti-check"></i></btn>' : '<btn class="btn btn-sm btn-danger btn-icon"><i class="fa ti-na"></i></btn>'?>
                                            
                                        </div>
                                        <div class="col-xs-1 text-center">
                                            <a href="?pagina=editarUser&cod=<?= $user->getCod();?>" class="btn btn-sm btn-info btn-icon" title="editar"><i class="fa ti-pencil-alt"></i></a>
                                        </div>
                                    </div>
                                </li>
                                <?php
                                        endforeach;
                                    endif;
                                ?>
                                
                            </ul>
                        </div>

                        <nav aria-label="Page navigation" style="margin: 10px;">
                            <ul class="pagination">
                                <li>
                                    <a href="#" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li>
                                    <a href="#" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>



                </div>
                <div class="col-lg-12 col-md-7">
                    
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Perfil</h4>
                        </div>
                        <div class="content">
                            <form method="post">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Usuário</label>
                                            <input type="text" name="txtUsuario" class="form-control border-input" placeholder="Usuário" value="<?= $usuario; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">E-mail</label>
                                            <input type="email" name="txtEmail" class="form-control border-input" placeholder="E-mail" value="<?= $email; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Status</label>
                                            <select name="slStatus" class="form-control border-input">
                                                <?php
                                                    if ($status == 1):
                                                        ?>
                                                        <option value="1" selected='selected'>Ativo</option>
                                                        <?php
                                                    else:
                                                        ?>
                                                        <option value="2" selected='selected'>Inativo</option>
                                                    <?php
                                                    endif;
                                                    if ($status != 1):
                                                        ?>
                                                        <option value="1" <?php $status == 1 ? "selected='selected'" : "" ?>>Ativo</option>
                                                        <?php
                                                    else:
                                                        ?>
                                                        <option value="2" <?php $status == 2 ? "selected='selected'" : "" ?>>Inativo</option>
                                                    <?php
                                                    endif;
                                                ?>
                                            </select>

                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label>Nome </label>
                                            <input type="text" name="txtNome" class="form-control border-input" placeholder="Nome" value="<?= $nome; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Senha</label>
                                            <input type="password" disabled="disable" name="txtSenha" class="form-control border-input" placeholder="**************" value="">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Nivel</label>
                                            <select name="slNivel" class="form-control border-input">                                                
                                                
                                                <?php
                                                    if ($nivel == 1):
                                                        ?>
                                                        <option value="1" selected='selected'>Super Admin</option>
                                                        <?php
                                                    else:
                                                        ?>
                                                        <option value="2" selected='selected'>Admin</option>
                                                    <?php
                                                    endif;
                                                    if ($nivel != 1):
                                                        ?>
                                                        <option value="1" <?php $nivel == 1 ? "selected='selected'" : "" ?>>Super Admin</option>
                                                        <?php
                                                    else:
                                                        ?>
                                                        <option value="2" <?php $nivel == 2 ? "selected='selected'" : "" ?>>Admin</option>
                                                    <?php
                                                    endif;
                                                ?>
                                                
                                                
                                            </select>

                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Cep</label>
                                            <input type="text" id="cep" name="txtCep" class="form-control border-input" placeholder="Cep" value="<?= $cep; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Bairro</label>
                                            <input type="text" id="bairro" name="txtBairro" class="form-control border-input" placeholder="Bairro" value="<?= $bairro; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Cidade</label>
                                            <input type="text" id="cidade" name="txtCidade" class="form-control border-input" placeholder="Cidade" value="<?= $cidade; ?>">
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label>Endereço</label>
                                            <input type="text" name="txtEndereco" id="rua" class="form-control border-input" placeholder="endereco" value="<?= $endereco; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label>Estado</label>
                                            <input type="text" name="txtEstado" id="uf" class="form-control border-input" placeholder="estado" value="<?= $estado; ?>">
                                        </div>
                                    </div>
                                </div>                               
                                <div class="row">
                                    <div class="col-md-12">
                                        <?php echo $resultado; ?>
                                    </div>
                                    
                                </div>                               


                                <div class="text-center">
                                    <input type="submit" class="btn btn-info btn-fill btn-wd" name="btnCadastrar" value="Atualizar">
                                </div>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>

