<?php
//intanciando os objetos
$usuarioController = new UsuarioController();
$usuarioModel = new Usuario();

//mostra a mensagem verdadeiro ou falso na hora do cadastro
$resultado = "";
$usuario = "";
$email = "";
$status = "";
$nome = "";
$nivel = "";
$cep = "";
$bairro = "";
$cidade = "";
$endereco = "";
$estado = "";

$btnCadastrar = filter_input(INPUT_POST, "btnCadastrar", FILTER_SANITIZE_STRING);
if ($btnCadastrar):
    $usuarioModel->setUsuario(filter_input(INPUT_POST, "txtUsuario", FILTER_SANITIZE_STRING));
    $usuarioModel->setEmail(filter_input(INPUT_POST, "txtEmail", FILTER_SANITIZE_STRING));
    $usuarioModel->setStatus(filter_input(INPUT_POST, "slStatus", FILTER_SANITIZE_NUMBER_INT));
    $usuarioModel->setNome(filter_input(INPUT_POST, "txtNome", FILTER_SANITIZE_STRING));
    $usuarioModel->setSenha(filter_input(INPUT_POST, "txtSenha", FILTER_SANITIZE_STRING));
    $usuarioModel->setNivel(filter_input(INPUT_POST, "slNivel", FILTER_SANITIZE_NUMBER_INT));
    $usuarioModel->setCep(filter_input(INPUT_POST, "txtCep", FILTER_SANITIZE_STRING));
    $usuarioModel->setBairro(filter_input(INPUT_POST, "txtBairro", FILTER_SANITIZE_STRING));
    $usuarioModel->setCidade(filter_input(INPUT_POST, "txtCidade", FILTER_SANITIZE_STRING));
    $usuarioModel->setEndereco(filter_input(INPUT_POST, "txtEndereco", FILTER_SANITIZE_STRING));
    $usuarioModel->setEstado(filter_input(INPUT_POST, "txtEstado", FILTER_SANITIZE_STRING));
    $usuarioModel->setData(date('Y-m-d H:i:s'));

    
    if ($usuarioController->Cadastrar($usuarioModel)):
        $resultado = '<div class="alert alert-success">
            <button type="button" aria-hidden="true" class="close">×</button>
            <span><b> Cadastro efetuado com sucesso - </b></span>
        </div>';
    else:
        $resultado = '<div class="alert alert-danger">
            <button type="button" aria-hidden="true" class="close">×</button>
            <span><b> Erro ao cadastrar, preencha todos os campos ou tente mais tarde. </b></span>
        </div>';
    endif;
    
      

endif;



?>

<div class="main-panel">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="#">Perfil Usuário</a>
            </div>
            <?php require_once './inc/header_top.php'; ?>
        </div>
    </nav>


    <div class="content">
        <div class="container-fluid">
            <div class="row">              

                    
                <div class="col-lg-12 col-md-7">
                    
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Perfil</h4>
                        </div>
                        <div class="content">
                            <form method="post">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Usuário</label>
                                            <input type="text" name="txtUsuario" class="form-control border-input" placeholder="Usuário" value="<?= $usuario; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">E-mail</label>
                                            <input type="email" name="txtEmail" class="form-control border-input" placeholder="E-mail" value="<?= $email; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Status</label>
                                            <select name="slStatus" class="form-control border-input">
                                                <option value="">Selecione o status</option>
                                                <option value="1">Ativo</option>
                                                <option value="2">Inativo</option>
                                            </select>

                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label>Nome </label>
                                            <input type="text" name="txtNome" class="form-control border-input" placeholder="Nome" value="<?= $nome; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Senha</label>
                                            <input type="text" name="txtSenha" class="form-control border-input" placeholder="Senha" value="">
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Nivel</label>
                                            <select name="slNivel" class="form-control border-input">
                                                <option value="">Selecione o Nível</option>
                                                <option value="1">Admin</option>
<!--                                                <option value="2">Admin</option>-->
                                            </select>

                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Cep</label>
                                            <input type="text" id="cep" name="txtCep" class="form-control border-input" placeholder="Cep" value="<?= $cep; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Bairro</label>
                                            <input type="text" id="bairro" name="txtBairro" class="form-control border-input" placeholder="Bairro" value="<?= $bairro; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Cidade</label>
                                            <input type="text" id="cidade" name="txtCidade" class="form-control border-input" placeholder="Cidade" value="<?= $cidade; ?>">
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label>Endereço</label>
                                            <input type="text" name="txtEndereco" id="rua" class="form-control border-input" placeholder="endereco" value="<?= $endereco; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label>Estado</label>
                                            <input type="text" name="txtEstado" id="uf" class="form-control border-input" placeholder="estado" value="<?= $estado; ?>">
                                        </div>
                                    </div>
                                </div>                               
                                <div class="row">
                                    <div class="col-md-12">
                                        <?php echo $resultado; ?>
                                    </div>
                                    
                                </div>                               


                                <div class="text-center">
                                    <input type="submit" class="btn btn-success btn-fill btn-wd" name="btnCadastrar" value="Cadastrar">
                                    <a href="?pagina=editarUser" class="btn btn-info btn-fill btn-wd">Editar Perfil</a>
                                </div>
                                
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
    
  
