
<div class="main-panel">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="#">Categoria</a>
            </div>
            <?php require_once './inc/header_top.php'; ?>
        </div>
    </nav>


    <div class="content">
        <div class="container-fluid">
            
<?php

    $userController = new UserController();
    $useModel = new User();
    
    $resultado = "";
    $nome = "";
    
    $btnCadastrar = filter_input(INPUT_POST, 'btnCadastrar', FILTER_SANITIZE_STRING);
    if($btnCadastrar):
        $useModel->setNome(filter_input(INPUT_POST, 'nome', FILTER_SANITIZE_STRING));
    if($userController->cadastrar($useModel)):
           $resultado = 'Cadastrado';    
        else:
           $resultado = 'error';
        
        endif;
    endif;

?>
            
            <div class="row">              
                <div class="col-lg-12 col-md-7">
                    <div class="card">
                        <div class="header">


                            <h4 class="title">Usuário</h4>
                        </div>
                        <div class="content">
                            <form method="post">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Cadastrar Usuario</label>
                                            <input type="text" name="nome" class="form-control border-input" placeholder="NOME">
                                        </div>
                                    </div>                                    
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                       <?php echo $resultado; ?>
                                    </div>
                                </div>                               

                                <div class="text-center">
                                    <input type="submit" class="btn btn-success btn-fill btn-wd" name="btnCadastrar" value="Cadastrar">
                                    <a href="?pagina=editarCat" class="btn btn-info btn-fill btn-wd">Editar Usuário</a>
                                </div>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>

