<?php
//instanciando as classes
$categoriaController = new CategoriaController();
$categoria = new Categoria();
$helper = new Helper();
$upload = new Upload();
$resultado = "";
?>
<div class="main-panel">

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="?pagina=listarProduto">Page Categoria</a>
            </div>
            <?php require_once './inc/header_top.php'; ?>
        </div>
    </nav>

    <div class="content">
        <div class="container-fluid">
            <div class="row">

                <form method="post">
                    <div class="col-lg-12 col-md-7">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Cadasstrar Categoria</h4>
                                <?php
                                $btnCadastrar = filter_input(INPUT_POST, 'btnCadastrar', FILTER_SANITIZE_STRING);
                                if ($btnCadastrar):
                                    $categoria->setTitulo(filter_input(INPUT_POST, 'txtTitulo', FILTER_SANITIZE_STRING));
                                    $url = $helper->Name($categoria->getTitulo());
                                    $categoria->setUrl($url);
                                    $categoria->setStatus(filter_input(INPUT_POST, 'slStatus', FILTER_SANITIZE_NUMBER_INT));
                                    $categoria->setDescricao(filter_input(INPUT_POST, 'txtDescricao', FILTER_SANITIZE_FULL_SPECIAL_CHARS));
                                    $categoria->setData(date('Y-m-d H:i:s'));
                                    
                                    //cadastro do categoria
                                    if ($categoriaController->Cadastrar($categoria)):

                                        //header("location: ?pagina=listarCategoria");
                                        $resultado = '<div class="alert alert-success">
                                                    <button type="button" aria-hidden="true" class="close">×</button>
                                                    <span><b> Cadastro efetuado com sucesso - </b></span>
                                                </div>';


                                    else:
                                        $resultado = '<div class="alert alert-danger">
                                                        <button type="button" aria-hidden="true" class="close">×</button>
                                                        <span><b> Erro ao cadastrar - Favor preencha todos os campos</b></span>
                                                    </div>';
                                    endif;
                                endif;
                                ?>
                            </div>

                            <div class="content">

                                <form method="post" enctype="multipart/form-data" id="frmCategoria" name="frmCategoria" novalidate onSubmit="return validaCadastro();" >
                                    
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Categoria</label>
                                                <input type="text" name="txtTitulo" id="txtTitulo" class="form-control border-input" placeholder="Categoria*" value="">
                                                <span class="msg-error msg-titulo"></span>
                                            </div>
                                        </div>                                    
                                    </div>                                                                       

                                    <div class="row">
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label>Descrição do Categoria</label>
                                                <input type="text" name="txtDescricao" class="form-control border-input" placeholder="Descrição da Categoria*" value="">

                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="slStatus">Status</label>
                                                <select name="slStatus" id="slStatus" class="form-control border-input">
                                                    <option value="">Selecione o Status</option>
                                                    <option value="1">Ativo</option>
                                                    <option value="2">Bloqueado</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <?= $resultado; ?>
                                        </div>

                                    </div>                                    

                                    <div class="text-center">
                                        <input type="submit" class="btn btn-info btn-fill btn-wd" name="btnCadastrar" value="Cadastrar Categoria"/>
                                        <a href="?pagina=listarCategoria" class="btn btn-warning btn-fill btn-wd" >Todas Categoria</a>
                                    </div>
                                    <div class="clearfix"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </form>
                
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function preview_images()
    {
        var total_file = document.getElementById("images").files.length;
        for (var i = 0; i < total_file; i++)
        {
            $('#image_preview').append("<div class='col-md-3'><img class='img-responsive' src='" + URL.createObjectURL(event.target.files[i]) + "'></div>");
        }
    }
</script>



