<?php
//instanciando os objetos
$categoria = new Categoria();
$categoriaController = new CategoriaController();
$helper = new Helper();
$upload = new Upload();
//mostra a mensagem verdadeiro ou falso na hora do cadastro
$resultado = "";

//alteração do post                             
$btnCadastrar = filter_input(INPUT_POST, 'btnCadastrar', FILTER_SANITIZE_STRING);
if ($btnCadastrar):      
     
    $cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);
    $categoria->setCod($cod);
    $categoria->setTitulo(filter_input(INPUT_POST, 'txtTitulo', FILTER_SANITIZE_STRING));
    $url = $helper->Name($categoria->getTitulo());
    $categoria->setUrl($url);
    $categoria->setStatus(filter_input(INPUT_POST, 'slStatus', FILTER_SANITIZE_NUMBER_INT));
    $categoria->setDescricao(filter_input(INPUT_POST, 'txtDescricao', FILTER_SANITIZE_SPECIAL_CHARS));
    $categoria->setData(date('Y-m-d H:i:s'));

   
    //Alterar do categoria
    if ($categoriaController->Atualizar($categoria)):   
        $insertGoTo = '?pagina=listarCategoria';
        header("refresh:2;url={$insertGoTo}");
        $resultado = '<div class="alert alert-success">
                        <button type="button" aria-hidden="true" class="close">×</button>
                        <span><b> Atualizado efetuado com sucesso - </b></span>
                    </div>';
    else:

        $insertGoTo = '?pagina=editarCategoria';
        header("refresh:2;url={$insertGoTo}");
        $resultado = '<div class="alert alert-danger">
                        <button type="button" aria-hidden="true" class="close">×</button>
                        <span><b> Erro ao Atualizar - Favor preencha todos os campos</b></span>
                    </div>';
    endif;

endif;

//retornando os dados para o formulário - atraves do get COD
$cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);
$retornaCategoria = $categoriaController->retornaCategoria($cod);
if ($retornaCategoria == NULL):

else:
   $nome = $retornaCategoria->getTitulo();
    $descricao = $retornaCategoria->getDescricao();    
    $status = $retornaCategoria->getStatus();
    ?>
    <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#">Page Categoria</a>
                </div>
                <?php require_once './inc/header_top.php'; ?>
            </div>
        </nav>


        <div class="content">
            <div class="container-fluid">
                <div class="row">

                    <form method="post" enctype="multipart/form-data">
                        <div class="col-lg-8 col-md-7">
                            <div class="card">
                                <div class="header">
                                    <h4 class="title">Editar Categoria</h4>                               

                                </div>
                                <div class="content">
                                    <form>                                  
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>Titulo Categoria</label>
                                                    <input type="text" class="form-control border-input" name="txtTitulo" placeholder="Categoria" value="<?= $nome; ?>">
                                                </div>
                                            </div>                                    
                                        </div>                                    


                                        <div class="row">
                                            <div class="col-md-8">
                                                <div class="form-group">
                                                    <label for="txtDescricao">Descrição da Categoria</label>
                                                    <input type="text" class="form-control border-input" name="txtDescricao" placeholder="Categoria" value=" <?= $descricao; ?>">
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="slStatus">Status</label>
                                                    <select name="slStatus" id="slStatus" class="form-control border-input" value=" <?= $status; ?>">
                                                        <?php
                                                        if ($status == 1):
                                                            ?>
                                                            <option value="1" selected='selected'>Ativo</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" selected='selected'>Bloqueado</option>
                                                        <?php
                                                        endif;
                                                        if ($status != 1):
                                                            ?>
                                                            <option value="1" <?php $status == 1 ? "selected='selected'" : "" ?>>Ativo</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" <?php $status == 2 ? "selected='selected'" : "" ?>>Bloqueado</option>
                                                        <?php
                                                        endif;
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-12">
                                                <?php echo $resultado; ?>
                                            </div>                                    
                                        </div>    


                                        <div class="text-center">
                                            <input type="submit" class="btn btn-success btn-fill btn-wd" name="btnCadastrar" value="Alterar Produto">
                                        </div>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </form>                   


                </div>
            </div>
        </div>
    <?php
    endif;
    ?>
    <script type="text/javascript">
        function preview_images()
        {
            var total_file = document.getElementById("images").files.length;
            for (var i = 0; i < total_file; i++)
            {
                $('#image_preview').append("<div class='col-md-3'><img class='img-responsive' src='" + URL.createObjectURL(event.target.files[i]) + "'></div>");
            }
        }
    </script>


