<?php
//instanciando os objetos
$post = new Post();
$postController = new PostController();
$helper = new Helper();
$categoriaController = new CategoriaController();
$upload = new Upload();

//mostra a mensagem verdadeiro ou falso na hora do cadastro
$resultado = "";

//alteração da imagem
$submitImage = filter_input(INPUT_POST, 'submitImage', FILTER_SANITIZE_STRING);
//if($submitImage):
//    var_dump($submitImage);    
//endif;


if ($submitImage):
    $cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);

    $retornaImagem = $postController->retornaPostImagem($cod);
    $thumbPost = $retornaImagem->getThumb();
    $nomePost = $retornaImagem->getTitulo();

    echo $capa = "../upload/" . $thumbPost;
    if (file_exists($capa) && !is_dir($capa)):
        unlink($capa);
    endif;
    //imagem esta recebendo files imagemArtigo
    $imagem = $_FILES['imagemArtigo'];
    //recebendo a imagem, nome do produto, tamanho da imagem, pasta
    $upload->Image($imagem, $nomePost, 1000, 'post');
    //setando a imagem
    $nomeImagem = $upload->getResult();
    $post->setThumb($nomeImagem);

    if ($postController->AlterarImagem($cod, $nomeImagem)):
        $insertGoTo = '?pagina=listarPost';
        header("refresh:2;url={$insertGoTo}");
        $resultado = "<div class=\"alert alert-success\">A imagem <b>{$nomeImagem} </b> foi alterado com sucesso</div>";
    else:
        $insertGoTo = '?pagina=produto';
        header("refresh:2;url={$insertGoTo}");
        $resultado = "<div class=\"alert alert-danger\">Erro ao cadastrar </div>";
    endif;
endif;

//alteração do post                             
$btnCadastrar = filter_input(INPUT_POST, 'btnCadastrar', FILTER_SANITIZE_STRING);
if ($btnCadastrar):
    $cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);
    $post->setCod($cod);
    $post->setTitulo(filter_input(INPUT_POST, 'txtTitulo', FILTER_SANITIZE_STRING));
    $url = $helper->Name($post->getTitulo());
    $post->setUrl($url);
    $post->setCategoria(filter_input(INPUT_POST, 'slCategoria', FILTER_SANITIZE_NUMBER_INT));
    $post->setStatus(filter_input(INPUT_POST, 'slStatus', FILTER_SANITIZE_NUMBER_INT));
    $post->setDescricao(filter_input(INPUT_POST, 'txtDescricao', FILTER_SANITIZE_SPECIAL_CHARS));
    $post->setData(date('Y-m-d H:i:s'));

    //Alterar do post
    if ($postController->Atualizar($post)):
//        $insertGoTo = '?pagina=listarPost';
//        header("refresh:2;url={$insertGoTo}");
        $resultado = '<div class="alert alert-success">
                        <button type="button" aria-hidden="true" class="close">×</button>
                        <span><b> Atualizado efetuado com sucesso - </b></span>
                    </div>';
    else:
//        $insertGoTo = '?pagina=editarPost';
//        header("refresh:2;url={$insertGoTo}");
        $resultado = '<div class="alert alert-danger">
                        <button type="button" aria-hidden="true" class="close">×</button>
                        <span><b> Erro ao Atualizar - Favor preencha todos os campos</b></span>
                    </div>';
    endif;

endif;

//retornando os dados para o formulário - atraves do get COD
$cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);
$retornaPost = $postController->retornaIdPost($cod);
if ($retornaPost == NULL):

else:
    $nome = $retornaPost->getTitulo();
    $postCat = $retornaPost->getCategoria();
    $descricao = $retornaPost->getDescricao();
    $thumb = $retornaPost->getThumb();
    $status = $retornaPost->getStatus();


    //pegando os dados da categoria
    $categCod = $retornaPost->getCategoria()->getCod();
    $categTitle = $retornaPost->getCategoria()->getTitulo();
    ?>
    <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#">Page Projetos</a>
                </div>
                <?php require_once './inc/header_top.php'; ?>
            </div>
        </nav>


        <div class="content">
            <div class="container-fluid">
                <div class="row">

                    <form method="post" enctype="multipart/form-data">
                        <div class="col-lg-8 col-md-7">
                            <div class="card">
                                <div class="header">
                                    <h4 class="title">Editar Projeto</h4>                               

                                </div>
                                <div class="content">
                                    <form>                                  
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>Titulo do Projeto</label>
                                                    <input type="text" class="form-control border-input" name="txtTitulo" placeholder="Projeto" value="<?= $nome; ?>">
                                                </div>
                                            </div>                                    
                                        </div>                                    


                                        <div class="row">
                                            <div class="col-md-8">
                                                <div class="form-group">
                                                    <label for="slCategoria">Categoria do Projeto</label>
                                                    <select id="slCategoria" name="slCategoria" class="form-control border-input">
                                                        <option value="<?= $categCod; ?>"><?= $categTitle; ?></option>                                                    

                                                        <?php
                                                        $listaCategoria = $categoriaController->ListarTodasCategorias();

                                                        if ($listaCategoria == NULL):
                                                            echo '<option value="">Não existem categoria cadastradas</option>';
                                                        else:

                                                            foreach ($listaCategoria as $cat):
                                                                if ($cat->getTitulo() == $categTitle):

                                                                else:
                                                                    echo "<option value={$cat->getCod()}>{$cat->getTitulo()}</option>";
                                                                endif;
                                                            endforeach;

                                                        endif;
                                                        ?>

                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="slStatus">Status de Projeto</label>
                                                    <select name="slStatus" id="slStatus" class="form-control border-input">
                                                        <?php
                                                        if ($status == 1):
                                                            ?>
                                                            <option value="1" selected='selected'>Ativo</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" selected='selected'>Bloqueado</option>
                                                        <?php
                                                        endif;
                                                        if ($status != 1):
                                                            ?>
                                                            <option value="1" <?php $status == 1 ? "selected='selected'" : "" ?>>Ativo</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" <?php $status == 2 ? "selected='selected'" : "" ?>>Bloqueado</option>
                                                        <?php
                                                        endif;
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>Descrição do Projeto</label>
                                                    <textarea rows="3" name="txtDescricao" class="form-control border-input" placeholder="Descrição do produto" >
                                                        <?= $descricao; ?>
                                                    </textarea>
                                                </div>
                                            </div>
                                        </div>                                                                     


                                        <div class="row">
                                            <div class="col-md-12">
                                                <?php echo $resultado; ?>
                                            </div>                                    
                                        </div>    


                                        <div class="text-center">
                                            <input type="submit" class="btn btn-success btn-fill btn-wd" name="btnCadastrar" value="Alterar Projeto">
                                        </div>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </form>

                    <div class="col-lg-4 col-md-5">
                        <div class="card card-user">
                            <div class="image">
                                <?php
                                if ($thumb == null):
                                    echo '<img id="img-uploaded" src="assets/img/no_image.jpg" alt="Sua imagem">';
                                else:
                                    echo "<img id='img-uploaded' src='../upload/{$thumb}' alt='Sua imagem'>";
                                endif;
                                ?>                            
                            </div>                        
                        </div>


                        <div class="card">
                            <div class="row" id="image_preview">                               
                            </div>
                            <div class="content">                            
                                <div class="row">                                 
                                    <form action="" method="post" enctype="multipart/form-data">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>CAPA (JPG 800X600PX):</label>
                                                <input type="file" class="form-control border-input uploader" id="imagemArtigo"  name="imagemArtigo">
                                            </div>
                                        </div>
                                        <div class="col-md-12 text-center">
                                            <input type="submit" class="btn btn-success btn-fill btn-wd" name='submitImage' value="Alterar Capa"/>
                                        </div>
                                    </form>                              
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
<?php
endif;
?>
<script type="text/javascript">
    function preview_images()
    {
        var total_file = document.getElementById("images").files.length;
        for (var i = 0; i < total_file; i++)
        {
            $('#image_preview').append("<div class='col-md-3'><img class='img-responsive' src='" + URL.createObjectURL(event.target.files[i]) + "'></div>");
        }
    }
</script>
